runMachAr : homework1.c ../NRs/ansi/recipes/machar.c ./machar_double.c ../NRs/ansi/other/nr.h ./myheader.h
	cc -o runMachAr homework1.c ../NRs/ansi/recipes/machar.c  ./machar_double.c -I ../NRs/ansi/other
