runMachAr : homework2.c ../NRs/ansi/recipes/bessj0.c ../NRs/ansi/recipes/bessj1.c ../NRs/ansi/recipes/zbrak.c ./rtbis.c ./rtflsp.c ./rtsec.c ./rtnewt.c ./rtsafe.c ./muller.c ./legendre.c ../NRs/ansi/other/nr.h  ./myheader.h
	cc -o runMachAr homework2.c ../NRs/ansi/recipes/bessj0.c ../NRs/ansi/recipes/bessj1.c ../NRs/ansi/recipes/zbrak.c ./rtbis.c ./rtflsp.c ./rtsec.c ./rtnewt.c ./rtsafe.c ./muller.c ./legendre.c -I ../NRs/ansi/other -I . -lm


