runMachAr : homework4.c ../NRs/ansi/recipes/ran1.c ../NRs/ansi/recipes/gasdev.c ../NRs/ansi/other/nr.h
	cc -o runMachAr homework4.c ../NRs/ansi/recipes/ran1.c ../NRs/ansi/recipes/gasdev.c -I  ../NRs/ansi/other
